"""create project_db

Revision ID: 87c9d6040e1d
Revises: 7aee8df6c398
Create Date: 2023-04-25 19:30:53.965851

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '87c9d6040e1d'
down_revision = '7aee8df6c398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
